### ISSUE TITLE
travis-ci is gone. Migrate to github actions.

### ISSUE THREAD

**Issue by smoser** [cirros-dev/cirros#76]
We were using travis-ci, it provided us with an amazing amount of function. It was too good to be true.
We need to migrate the .travis.yml to github actions , or some other magical platform that has free compute time.

**Comment by NucciTheBoss** [comment]
Would be willing to help with this to help keep CirrOS compatible with newer systems (see #77). In my case, my tempest functional tests fail since CirrOS does not currently support `rsa-sha2`. Luckily, it looks like GitHub has a documentation page published to help folks migrate from Travis CI to GitHub Actions: https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions. Since this repository is public it looks that we can use it for free.
